core_home:
    path:     /
    defaults: { _controller: CoreBundle:Home:index, page: 1 }

core_inscription:
    path:     /inscription
    defaults: { _controller: CoreBundle:INCP:index, page: 2 }

core_connexion:
    path:     /connexion
    defaults: { _controller: CoreBundle:CNX:index, page: 3 }

core_blog:
    path:     /blog
    defaults: { _controller: CoreBundle:Blog:index, page: 4 }

core_commu:
    path:     /commu
    defaults: { _controller: CoreBundle:Commu:index, page: 5 }

core_forums:
    path:     /forums
    defaults: { _controller: CoreBundle:Forums:index, page: 6 }

core_boutique:
    path:    /boutique
    defaults: { _controller: CoreBundle:Home:boutique }
