core_home:
    path:     /
    defaults: { _controller: CoreBundle:Home:index }

core_contact:
    path:     /contact
    defaults: { _controller: CoreBundle:Home:contact }

core_mentions:
    path:     /mentions
    defaults: { _controller: CoreBundle:Home:mentions }

core_inscription:
    path:     /inscription
    defaults: { _controller: CoreBundle:INCP:index }

core_connexion:
    path:     /connexion
    defaults: { _controller: CoreBundle:CNX:index }

core_deconnexion:
    path:     /deconnexion
    defaults: { _controller: CoreBundle:DCNX:index }
