core_home:
    path:     /
    defaults: { _controller: CoreBundle:Home:index }

core_contact:
    path:     /contact
    defaults: { _controller: CoreBundle:Home:contact }

core_mentions:
    path:     /mentions
    defaults: { _controller: CoreBundle:Home:mentions }

core_equipe:
    path:     /equipe
    defaults: { _controller: CoreBundle:Home:equipe }
