core_home:
    path:     /
    defaults: { _controller: CoreBundle:Home:index }

core_contact:
    path:     /contact
    defaults: { _controller: CoreBundle:Home:contact }

core_mentions:
    path:     /mentions
    defaults: { _controller: CoreBundle:Home:mentions }

core_equipe:
    path:     /equipe
    defaults: { _controller: CoreBundle:Home:equipe }

# Définition des routes pour le back office #

back_office:
    path:     /back_office
    defaults: { _controller: CoreBundle:Back:back }

back_office_add:
    path:     /back_office/addAction
    defaults: { _controller: CoreBundle:Back:add }


back_office_update:
    path:     /back_office/update/{id}
    defaults: { _controller: CoreBundle:Back:update }
    requirements:
        id: \d+

back_office_delete:
    path:     /back_office/delete/{id}
    defaults: { _controller: CoreBundle:Back:delete }
    requirements:
        id: \d+

back_office_delete_commentaires:
    path:     /back_office/delete/commentaires/{id}
    defaults: { _controller: CoreBundle:Back:delete }
    requirements:
        id: \d+

# Définition des routes pour les profils #

back_office_lock_user:
    path:     /back_office/user/lock
    defaults: { _controller: CoreBundle:Back:lockUser }

back_office_change_role:
    path:     /back_office/user/role
    defaults: { _controller: CoreBundle:Back:roleUser }
