# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    core.blog:
        class: CoreBundle\Outils\Blog
        arguments: ['@doctrine.orm.entity_manager', '@session', '@router', '@security.token_storage', '@form.factory', '@core.slugger']

    core.slugger:
        class: CoreBundle\Outils\Slug

    core.purge:
        class: CoreBundle\Outils\Purge
        arguments: ['@doctrine.orm.entity_manager']
