<?php

namespace UserBundle\Repository;

/**
 * RefeshTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefeshTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
