<?php

namespace BlogBundle\Repository;

/**
 * Article_membreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Article_membreRepository extends \Doctrine\ORM\EntityRepository
{
}
