# Déclarations des routes globales #
forums_home:
    path:     /forums
    defaults: { _controller: ForumsBundle:Forums:index }

forums_view:
    path:     /forums/view/{id}
    defaults: { _controller: ForumsBundle:Forums:view }
    requirements:
        id: \d+

forums_delete:
    path:     /forums/delete/{id}
    defaults: { _controller: ForumsBundle:Forums:delete }
    requirements:
        id: \d+

# Défintion des routes du forum General #

forums_general:
    path:     /general
    defaults: { _controller: ForumsBundle:General:index }

forums_general_add:
    path:     /general/Add
    defaults: { _controller: ForumsBundle:General:add }



forums_consoles:
    path:     /consoles
    defaults : { _controller: ForumsBundle:Forums:consoles }

forums_pc:
    path:     /pc
    defaults: { _controller: ForumsBundle:Forums:pc }

forums_admin:
    path:     /admin
    defaults: { _controller: ForumsBundle:Forums:admin }
