# Déclarations des routes globales #
forums_home:
    path:     /forums
    defaults: { _controller: ForumsBundle:Forums:index }

forums_view:
    path:     /forums/view/{id}
    defaults: { _controller: ForumsBundle:Forums:view }
    requirements:
        id: \d+

forums_delete:
    path:     /forums/delete/{id}
    defaults: { _controller: ForumsBundle:Forums:delete }
    requirements:
        id: \d+

forums_update:
    path:     /forums/update/{id}
    defaults: { _controller: ForumsBundle:Forums:update }
    requirements:
        id: \d+

# Défintion des routes du forum General #

forums_general:
    path:     /general
    defaults: { _controller: ForumsBundle:General:index }

forums_general_add:
    path:     /general/add
    defaults: { _controller: ForumsBundle:General:add }

# Défintion des routes du forum Consoles #

forums_consoles:
    path:     /consoles
    defaults : { _controller: ForumsBundle:Console:index }

forums_consoles_add:
    path:     /consoles/add
    defaults: { _controller: ForumsBundle:Console:add }

# Définition des routes du forum PC #

forums_pc:
    path:     /pc
    defaults: { _controller: ForumsBundle:Pc:index }

forums_pc_add:
    path:     /pc/add
    defaults: { _controller: ForumsBundle:Pc:add }

# Définition des routes du forum Admin #

forums_admin:
    path:     /admin
    defaults: { _controller: ForumsBundle:Admin:index }

forums_admin_add:
    path:     /admin/add
    defaults: { _controller: ForumsBundle:Admin:add }
