forums_home:
    path:     /forums
    defaults: { _controller: ForumsBundle:Forums:index }

forums_view:
    path:     /forums/view/{id}
    defaults: { _controller: ForumsBundle:Forums:view }

forums_general:
    path:     /general
    defaults: { _controller: ForumsBundle:Forums:general }

forums_consoles:
    path:     /consoles
    defaults : { _controller: ForumsBundle:Forums:consoles }

forums_pc:
    path:     /pc
    defaults: { _controller: ForumsBundle:Forums:pc }

forums_admin:
    path:     /admin
    defaults: { _controller: ForumsBundle:Forums:admin }
