user_login:
    path:     /login
    defaults: { _controller: UserBundle:Default:index }

user_logout:
    path:     /logout
    defaults: { _controller: UserBundle:Logout:index }

user_register:
    path:     /register
    defaults: { _controller: UserBundle:Register:index }
