<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

  public function getArticle($categorie)
  {
    return $this->createQueryBuilder('ab')
                ->where('ab.categorie = :categorie')
                  ->setParameter('categorie', $categorie)
                ->orderBy('ab.datePublication', 'DESC')
                ->getQuery()
                ->getResult();
  }

  public function showArticles($categorie)
  {
    return $this->createQueryBuilder('ab')
                ->where('ab.categorie = :categorie')
                  ->setParameter('categorie', array($categorie))
                ->orderBy('ab.datePublication', 'DESC')
                ->setMaxResults(3)
                ->getQuery()
                ->getResult();
  }

  public function getUpdateArticle($id)
  {
      return $this->createQueryBuilder('a')
                  ->where('a.id = :id')
                    ->setParameter('id', $id)
                  ->getQuery()
                  ->getResult();
  }

  public function getPublication($auteur)
  {
    return $this->createQueryBuilder('up')
                ->where('up.auteur = :auteur')
                  ->setParameter('auteur', $auteur)
                ->getQuery()
                ->getResult();
  }
}
