<?php

namespace CoreBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
  public function getCommentaires()
  {
    return $this->createQueryBuilder('c')
                ->getQuery()
                ->getResult();
  }

  public function removeCommentaire($id)
  {
    return $this->createQueryBuilder('com')
                ->where('com.id = :id')
                  ->setParameter('id', $id)
                ->delete()
                ->getQuery()
                ->getResult();
  }
}
