<?php

namespace ForumsBundle\Repository;

/**
 * ForumsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumsRepository extends \Doctrine\ORM\EntityRepository
{
  public function getSujet()
  {
    return $this->createQueryBuilder('f')
                ->leftJoin('f.sujet', 's')
                ->where('f.sujet = :sujet')
                  ->setParameter('sujet')
                ->getQuery()
                ->getResult();
  }
}
