<?php

namespace ForumsBundle\Repository;

/**
 * SujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetRepository extends \Doctrine\ORM\EntityRepository
{
  public function getSujetGeneral()
  {
    return $this->createQueryBuilder('sg')
                ->where('sg.category = :category')
                  ->setParameter('category', 'General')
                ->orderBy('sg.dateCreation', 'DESC')
                ->getQuery()
                ->getResult();
  }

  public function getSujetConsoles()
  {
    return $this->createQueryBuilder('sc')
                ->where('sc.category = :category')
                  ->setParameter('category', 'Consoles')
                ->orderBy('sc.dateCreation', 'DESC')
                ->getQuery()
                ->getResult();
  }

  public function getSujetPC()
  {
    return $this->createQueryBuilder('sp')
                ->where('sp.category = :category')
                  ->setParameter('category', 'Pc')
                ->orderBy('sp.dateCreation', 'DESC')
                ->getQuery()
                ->getResult();
  }

  public function getSujetAdmin()
  {
    return $this->createQueryBuilder('sa')
                ->where('sa.category = :category')
                  ->setParameter('category', 'Admin')
                ->orderBy('sa.dateCreation', 'DESC')
                ->getQuery()
                ->getResult();
  }

  public function removeSujet($id)
  {
    /* On sélectionne l'article selon ID, on y joint les messages puis on supprime le sujet */
    return $this->createQueryBuilder('a')
                ->leftJoin('a.messages', 'msg')
                  ->addSelect('msg')
                ->where('a.id = :id')
                  ->setParameter('id', $id)
                ->delete()
                ->getQuery()
                ->getResult();
  }
}
